name:                stack-bug-report
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/stack-bug-report#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - hedgehog >= 1.0
  - tasty-hedgehog == 1.0.0.1

executables:
  stack-bug-report:
    source-dirs:      src
    main:             Main.hs
